# Generated by Django 6.0.7 on 2026-07-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(max_length=100)),
                ('image_url', models.TextField(blank=True, default='')),
                ('careers', models.TextField(blank=True, default='')),
                ('courses', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
    ]
