# Generated by Django 6.0.7 on 2026-07-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('image_url', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('specs', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'labs',
            },
        ),
    ]
