# Generated by Django 6.0.7 on 2026-07-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lab'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
                ('official_fee', models.CharField(max_length=100)),
                ('discounted_fee', models.CharField(max_length=100)),
                ('installment', models.CharField(max_length=100)),
                ('payment_options', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tuition_fees',
            },
        ),
    ]
